// Generated by CoffeeScript 1.9.1
(function() {
  var board;

  board = require("../src/board");

  describe("board", function() {
    var blockToOpen, game, player;
    player = 0;
    game = 0;
    blockToOpen = 0;
    beforeEach(function() {
      blockToOpen = {
        x: {
          start: 6,
          end: 0,
          line: {
            pos: 3,
            axis: "x"
          }
        },
        y: {
          start: 6,
          end: 0,
          line: {
            pos: 3,
            axis: "y"
          }
        }
      };
      game = new board.Board(9);
      player = {
        pos: {
          x: 3,
          y: 3
        },
        name: 'alonso'
      };
      return game.addPlayer(player);
    });
    it("create a board 9x9", function() {
      return expect(game.getSize()).toBe(9);
    });
    it("can save player", function() {
      var players;
      players = game.getPlayers();
      return expect(players.length).toBe(1);
    });
    it("get the correct player by name", function() {
      var savedPlayer;
      savedPlayer = game.getPlayer(player.name);
      return expect(savedPlayer).toEqual(player);
    });
    it("player is saved correctly", function() {
      var players;
      players = game.getPlayers();
      return expect(players[0]).toEqual(player);
    });
    it("board open X blocks ", function() {
      var open;
      game.openBlocks(blockToOpen.x);
      open = game.isBlockOpen(6, 3);
      return expect(open).toBeTruthy();
    });
    it("board open Y blocks ", function() {
      var open;
      game.openBlocks(blockToOpen.y);
      open = game.isBlockOpen(3, 6);
      return expect(open).toBeTruthy();
    });
    it("player can move north", function() {
      game.openBlocks(blockToOpen.x);
      game.movePlayer(player.name, "up");
      return expect(player.pos.y).toBe(4);
    });
    return it("player can move west", function() {
      game.openBlocks(blockToOpen.y);
      game.movePlayer(player.name, "left");
      return expect(player.pos.x).toBe(2);
    });
  });

}).call(this);

//# sourceMappingURL=board.spec.js.map
