// Generated by CoffeeScript 1.9.1
(function() {
  var Game;

  Game = (function() {
    function Game(board) {
      this.board = board;
      this.players = [];
    }

    Game.prototype.addPlayer = function(player) {
      this.players.push(player);
      return player.sight = this.board.generateSight(player.pos);
    };

    Game.prototype.getPlayers = function() {
      return this.players;
    };

    Game.prototype.getPlayer = function(name) {
      var i, len, player, ref;
      ref = this.players;
      for (i = 0, len = ref.length; i < len; i++) {
        player = ref[i];
        if (player.name === name) {
          return player;
        }
      }
      throw new Error("Player not fond");
    };

    Game.prototype.movePlayer = function(name, dir) {
      var player, speed;
      speed = dir === "up" || dir === "right" ? 1 : -1;
      player = this.getPlayer(name);
      if (dir === "up" || dir === "down") {
        return player.pos.y += speed;
      } else {
        return player.pos.x += speed;
      }
    };

    return Game;

  })();

  module.exports = Game;

}).call(this);
