// Generated by CoffeeScript 1.9.1
(function() {
  var app, express, http, io, jade, server, socket, views;

  express = require('express');

  socket = require('socket.io');

  jade = require('jade');

  app = express();

  http = require('http').Server(app);

  io = socket(http);

  views = [];

  views['index'] = jade.compileFile(__dirname + "/view/index.jade");

  app.get('/', function(req, res) {
    return res.send(views['index']());
  });

  app.use('/static', express["static"](__dirname + "/public"));

  app.use('/test', express["static"](__dirname + "/public-test"));

  server = app.listen(3000, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('Example app listening at http://%s:%s', host, port);
  });

}).call(this);
